export enum NotificationType {
  CHAT_MESSAGE = 1000,
  STATUS_LIKE,
  STATUS_DISLIKE,
  STATUS_SHARE,
  STATUS_REPLY,
  CONTACT_NEW_STATUS,
  CONTACT_LIVE_VIDEO,
  CONTACT_NEW_REG,
  COMMENT_REPLY,
  TOP_GLOBAL_MEDIA,
}
